### ISSUE TITLE
Strange error while running live image using qemu ..

### ISSUE THREAD

**Issue by gkammela** [intel/luv-yocto#64] opened 2015-09-30 02:21 UTC
when ran LUV using qemu ( below is the command)
$ runqemu qemux86-64 biosdir="tmp/sysroots/x86_64-linux/usr/share/ovmf" ramfs core-image-efi-initramfs
It ran till it shows up the luv-version and then seems to hang there for a while, which doesn't seem to be good. 

below is the log:
Linux UEFI Validation Distribution 2.0-dev qemux86-64 ttyS0

qemux86-64 login: [   29.601578] cfg80211: Calling CRDA to update world regulatory domain
[   32.752413] cfg80211: Calling CRDA to update world regulatory domain
[   35.905839] cfg80211: Exceeded CRDA call max attempts. Not calling CRDA
INIT: Id "S1" respawning too fast: disabled for 5 minutes
INIT: Id "S1" respawning too fast: disabled for 5 minutes
INIT: Id "S1" respawning too fast: disabled for 5 minutes

**Comment by ricardon** [comment] 2015-10-02 00:53
This behavior is also observed in aarch64: https://lists.01.org/pipermail/luv/2015-October/000636.html.

I wonder if this is caused by *not* having a /dev/ttyS1 as detailed here: 

http://www.tldp.org/HOWTO/Text-Terminal-HOWTO-19.html#rapid_respawn

**Comment by ricardon** [comment] 2015-10-09 13:59
Calling getty by hand on S1 returns with status 1. Needs to investigate. On a side note, LUV uses SysV. Should we consider systemd for improved serial console handling?

**Comment by meghadey** [comment] 2017-10-26 00:09
check if this issue is observed with systemd

**Comment by meghadey** [comment] 2018-06-14 00:01
This issue has not been observed after shifting to systemd. Hence closing it.

**Closed by meghadey** 2018-06-14 00:01 UTC
